version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: api-flask

    container_name: postgres-app
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend-app:
    image: hiagocelestino/backend-app:1.1
    container_name: backend-app
    ports:
      - 5000:5000
    depends_on:
      - postgres
  
  frontend-app:
    image: hiagocelestino/frontend-app:1.0
    container_name: frontend-app
    ports:
      - 3000:3000
    depends_on:
      - backend-app

volumes:
  db-app-volume:
